from karen.actions.actionData import GOH_HIT_DISPLACE_DELAY

COMBO_ACTION_SYMBOLS = {
    "p" : ["p"],
    "k" : ["k"],
    "o" : ["o"],
    "t" : ["t"],
    "w" : ["w"],
    "s" : ["w"],
    "a" : ["a"],
    "g" : ["g"],
    "G" : ["G"],
    "u" : ["u"],
    "S" : ["S"],
    "V" : ["V"],
    "v" : ["V"],
    "C" : ["C"],
    "c" : ["C"],
    "B" : ["B"],
    "b" : ["B"],
    "E" : ["E"],
    "e" : ["E"],
    "+" : ["+"],
    "-" : ["-"],
    "f" : ["G", "+", "u"],
    "j" : ["u", "+", "w", "+", "G"],
    "," : [","]
}

COMBO_ACTION_NAMES = {
    "punch" : ["p"],
    "melee" : ["p"],
    "meleepunch" : ["p"],

    "kick" : ["k"],
    "meleekick" : ["k"],

    "overheadslam" : ["o"],
    "overhead" : ["o"],
    "over" : ["o"],
    "oh" : ["o"],
    "downslam" : ["o"],
    "slam" : ["o"],
    "meleeoverheadslam" : ["o"],
    "meleeoverhead" : ["o"],
    "meleeover" : ["o"],
    "meleeoh" : ["o"],
    "meleedownslam" : ["o"],
    "meleeslam" : ["o"],

    "tracer" : ["t"],
    "webtracer" : ["t"],
    "cluster" : ["t"],
    "webcluster" : ["t"],

    "swingwhiff" : ["w"],
    "webswingwhiff" : ["w"],
    "whiff" : ["w"],
    "webwhiff" : ["w"],
    "swing" : ["w"],
    "webswing" : ["w"],

    "autoswing" : ["a"],
    "autowebswing" : ["a"],
    "auto" : ["a"],
    "autoweb" : ["a"],
    "simpleswing" : ["a"],
    "simplewebswing" : ["a"],
    "simple" : ["a"],
    "simpleweb" : ["a"],
    "easyswing" : ["a"],
    "easywebswing" : ["a"],
    "easy" : ["a"],
    "easyweb" : ["a"],
    "highswing" : ["a"],
    "highwebswing" : ["a"],

    "getoverhere" : ["g"],
    "goh" : ["g"],
    "web pull" : ["g", f"[{GOH_HIT_DISPLACE_DELAY}f]"],
    "pull" : ["g", f"[{GOH_HIT_DISPLACE_DELAY}f]"],

    "getoverheretargeting" : ["G"],
    "getoverheretargetting" : ["G"],
    "goht" : ["G"],

    "uppercut" : ["u"],
    "upper" : ["u"],
    "amazingcombo" : ["u"],

    "symbiote" : ["S"],
    "symbiot" : ["S"],

    "venom" : ["V"],
    "venomsymbiote" : ["V"],
    "venomsymbiot" : ["V"],
    "upgradedsymbiote" : ["V"],
    "upgradedsymbiot" : ["V"],

    "clap" : ["C"],
    "peniclap" : ["C"],

    "webbomb" : ["B"],
    "bomb" : ["B"],
    "peniwebbomb" : ["B"],
    "penibomb" : ["B"],

    "explosion" : ["E"],
    "webexplosion" : ["E"],
    "exp" : ["E"],
    "peniexplosion" : ["E"],
    "peniwebexplosion" : ["E"],
    "peniexp" : ["E"],

    "ffamestack" : ["G", "+", "u"],
    "ffame" : ["G", "+", "u"],

    "punchsaporen" : ["p" , "+", "G"],
    "punchsaporentech" : ["p" , "+", "G"],

    "kicksaporen" : ["k" , "+", "G"],
    "kicksaporentech" : ["k" , "+", "G"],

    "overheadslamsaporen" : ["o" , "+", "G"],
    "overheadslamsaporentech" : ["o" , "+", "G"],
    "overheadsaporen" : ["o" , "+", "G"],
    "overheadsaporentech" : ["o" , "+", "G"],
    "ohsaporen" : ["o" , "+", "G"],
    "ohsaporentech" : ["o" , "+", "G"],
    "downslamsaporen" : ["o" , "+", "G"],
    "downslamsaporentech" : ["o" , "+", "G"],
    "slamsaporen" : ["o" , "+", "G"],
    "slamsaporentech" : ["o" , "+", "G"],
    "saporen" : ["o" , "+", "G"],
    "saporentech" : ["o" , "+", "G"],

    "punchsaporenffamestack" : ["p", "+", "G", "+", "u"],
    "punchsaporenffame" : ["p", "+", "G", "+", "u"],
    "punchsapstack" : ["p", "+", "G", "+", "u"],
    "punchsapostack" : ["p", "+", "G", "+", "u"],

    "kicksaporenffamestack" : ["k", "+", "G", "+", "u"],
    "kicksaporenffame" : ["k", "+", "G", "+", "u"],
    "kicksapstack" : ["k", "+", "G", "+", "u"],
    "kicksapostack" : ["k", "+", "G", "+", "u"],

    "overheadslamsaporenffamestack" : ["o", "+", "G", "+", "u"],
    "overheadslamsaporenffame" : ["o", "+", "G", "+", "u"],
    "overheadslamsapostack" : ["o", "+", "G", "+", "u"],
    "overheadslamsapstack" : ["o", "+", "G", "+", "u"],
    "overheadsaporenffamestack" : ["o", "+", "G", "+", "u"],
    "overheadsaporenffame" : ["o", "+", "G", "+", "u"],
    "overheadsapostack" : ["o", "+", "G", "+", "u"],
    "overheadsapstack" : ["o", "+", "G", "+", "u"],
    "ohsaporenffamestack" : ["o", "+", "G", "+", "u"],
    "ohsaporenffame" : ["o", "+", "G", "+", "u"],
    "ohsapostack" : ["o", "+", "G", "+", "u"],
    "ohsapstack" : ["o", "+", "G", "+", "u"],
    "downslamsaporenffamestack" : ["o", "+", "G", "+", "u"],
    "downslamsaporenffame" : ["o", "+", "G", "+", "u"],
    "downslamsapostack" : ["o", "+", "G", "+", "u"],
    "downslamsapstack" : ["o", "+", "G", "+", "u"],
    "slamsaporenffamestack" : ["o", "+", "G", "+", "u"],
    "slamsaporenffame" : ["o", "+", "G", "+", "u"],
    "slamsapostack" : ["o", "+", "G", "+", "u"],
    "slamsapstack" : ["o", "+", "G", "+", "u"],
    "saporenffamestack" : ["o", "+", "G", "+", "u"],
    "saporenffame" : ["o", "+", "G", "+", "u"],
    "sapostack" : ["o", "+", "G", "+", "u"],
    "sapstack" : ["o", "+", "G", "+", "u"],

    "spacejam" : ["u", "+", "w", "+", "G"],

    "fastspacejam" : ["u", "+", "a", "+", "G"],
    "autoswingspacejam" : ["u", "+", "a", "+", "G"],
    "autospacejam" : ["u", "+", "a", "+", "G"],

    "punchreversetrigger" : ["p", "+", "t"],
    "punchrt" : ["p", "+", "t"],
    "reversetrigger" : ["p", "+", "t"],
    "rt" : ["p", "+", "t"],

    "kickreversetrigger" : ["k", "+", "t"],
    "kickrt" : ["k", "+", "t"],

    "overheadslamreversetrigger" : ["o", "+", "t"],
    "overheadslamrt" : ["o", "+", "t"],
    "overheadreversetrigger" : ["o", "+", "t"],
    "overheadrt" : ["o", "+", "t"],
    "ohreversetrigger" : ["o", "+", "t"],
    "ohrt" : ["o", "+", "t"],
    "downslamreversetrigger" : ["o", "+", "t"],
    "downslamrt" : ["o", "+", "t"],
    "slamreversetrigger" : ["o", "+", "t"],
    "slamrt" : ["o", "+", "t"],

    "uniquestack" : ["p", "+", "o"],
    "uniquepunchstack" : ["p", "+", "o"],
    "uniquepunchoverheadslamstack" : ["p", "+", "o"],
    "uniquepunchoverheadstack" : ["p", "+", "o"],
    "uniquepunchohstack" : ["p", "+", "o"],
    "uniquepunchdownslamstack" : ["p", "+", "o"],
    "uniquepunchslamstack" : ["p", "+", "o"],

    "uniquekickstack" : ["p", "+", "o"],
    "uniquekickoverheadslamstack" : ["p", "+", "o"],
    "uniquekickoverheadstack" : ["p", "+", "o"],
    "uniquekickohstack" : ["p", "+", "o"],
    "uniquekickdownslamstack" : ["p", "+", "o"],
    "uniquekickslamstack" : ["p", "+", "o"],

    "gohbombstack" : ["g", "+", "B"],
    "getoverherebombstack" : ["g", "+", "B"],
    "pullbombstack" : ["g", "+", "B"],
    "webpullbombstack" : ["g", "+", "B"],

    "gohtbombstack" : ["G", "+", "B"],
    "getoverheretargetingbombstack" : ["G", "+", "B"],
    "getoverheretargettingbombstack" : ["G", "+", "B"],

    "punchexplosionsaporenffamestack" : ["p", "+", "E", "+", "G", "+", "u"],
    "punchexplosionsaporenffame" : ["p", "+", "E", "+", "G", "+", "u"],
    "punchexplosionsapstack" : ["p", "+", "E", "+", "G", "+", "u"],
    "punchexplosionsapostack" : ["p", "+", "E", "+", "G", "+", "u"],

    "kickexplosionsaporenffamestack" : ["k", "+", "E", "+", "G", "+", "u"],
    "kickexplosionsaporenffame" : ["k", "+", "E", "+", "G", "+", "u"],
    "kickexplosionsapstack" : ["k", "+", "E", "+", "G", "+", "u"],
    "kickexplosionsapostack" : ["k", "+", "E", "+", "G", "+", "u"],

    "overheadslamexplosionsaporenffamestack" : ["o", "+", "E", "+", "G", "+", "u"],
    "overheadslamexplosionsaporenffame" : ["o", "+", "E", "+", "G", "+", "u"],
    "overheadslamexplosionsapostack" : ["o", "+", "E", "+", "G", "+", "u"],
    "overheadslamexplosionsapstack" : ["o", "+", "E", "+", "G", "+", "u"],
    "overheadexplosionsaporenffamestack" : ["o", "+", "E", "+", "G", "+", "u"],
    "overheadexplosionsaporenffame" : ["o", "+", "E", "+", "G", "+", "u"],
    "overheadexplosionsapostack" : ["o", "+", "E", "+", "G", "+", "u"],
    "overheadexplosionsapstack" : ["o", "+", "E", "+", "G", "+", "u"],
    "ohexplosionsaporenffamestack" : ["o", "+", "E", "+", "G", "+", "u"],
    "ohexplosionsaporenffame" : ["o", "+", "E", "+", "G", "+", "u"],
    "ohexplosionsapostack" : ["o", "+", "E", "+", "G", "+", "u"],
    "ohexplosionsapstack" : ["o", "+", "E", "+", "G", "+", "u"],
    "downslamexplosionsaporenffamestack" : ["o", "+", "E", "+", "G", "+", "u"],
    "downslamexplosionsaporenffame" : ["o", "+", "E", "+", "G", "+", "u"],
    "downslamexplosionsapostack" : ["o", "+", "E", "+", "G", "+", "u"],
    "downslamexplosionsapstack" : ["o", "+", "E", "+", "G", "+", "u"],
    "slamexplosionsaporenffamestack" : ["o", "+", "E", "+", "G", "+", "u"],
    "slamexplosionsaporenffame" : ["o", "+", "E", "+", "G", "+", "u"],
    "slamexplosionsapostack" : ["o", "+", "E", "+", "G", "+", "u"],
    "slamexplosionsapstack" : ["o", "+", "E", "+", "G", "+", "u"],
    "explosionsaporenffamestack" : ["o", "+", "E", "+", "G", "+", "u"],
    "explosionsaporenffame" : ["o", "+", "E", "+", "G", "+", "u"],
    "explosionsapostack" : ["o", "+", "E", "+", "G", "+", "u"],
    "explosionsapstack" : ["o", "+", "E", "+", "G", "+", "u"],

    "uniquepunchexplosionoverheadslamstack" : ["p", "+", "E", "+", "o"],
    "uniquepunchexplosionoverheadstack" : ["p", "+", "E", "+", "o"],
    "uniquepunchexplosionohstack" : ["p", "+", "E", "+", "o"],
    "uniquepunchexplosiondownslamstack" : ["p", "+", "E", "+", "o"],
    "uniquepunchexplosionslamstack" : ["p", "+", "E", "+", "o"],

    "uniquekickexplosionstack" : ["p", "+", "E", "+", "o"],
    "uniquekickexplosionoverheadslamstack" : ["p", "+", "E", "+", "o"],
    "uniquekickexplosionoverheadstack" : ["p", "+", "E", "+", "o"],
    "uniquekickexplosionohstack" : ["p", "+", "E", "+", "o"],
    "uniquekickexplosiondownslamstack" : ["p", "+", "E", "+", "o"],
    "uniquekickexplosionslamstack" : ["p", "+", "E", "+", "o"],

    "symbioticspacejam" : ["u", "+", "S", "+", "w", "+", "G"],
    "symbiotespacejam" : ["u", "+", "S", "+", "w", "+", "G"],
    
    "fastsymbioticspacejam" : ["u", "+", "S", "+", "a", "+", "G"],
    "autoswingsymbioticspacejam" : ["u", "+", "S", "+", "a", "+", "G"],
    "autosymbioticspacejam" : ["u", "+", "S", "+", "a", "+", "G"],
    "fastsymbiotespacejam" : ["u", "+", "S", "+", "a", "+", "G"],
    "autoswingsymbiotespacejam" : ["u", "+", "S", "+", "a", "+", "G"],
    "autosymbiotespacejam" : ["u", "+", "S", "+", "a", "+", "G"],

    "punchcancel" : ["p-"],
    "meleecancel" : ["p-"],
    "meleepunchcancel" : ["p-"],
    "punchburn" : ["p-"],
    "meleeburn" : ["p-"],
    "meleepunchburn" : ["p-"],

    "kickcancel" : ["k-"],
    "meleekickcancel" : ["k-"],
    "kickburn" : ["k-"],
    "meleekickburn" : ["k-"],

    "overheadslamcancel" : ["o-"],
    "overheadcancel" : ["o-"],
    "overcancel" : ["o-"],
    "ohcancel" : ["o-"],
    "downslamcancel" : ["o-"],
    "slamcancel" : ["o-"],
    "meleeoverheadslamcancel" : ["o-"],
    "meleeoverheadcancel" : ["o-"],
    "meleeovercancel" : ["o-"],
    "meleeohcancel" : ["o-"],
    "meleedownslamcancel" : ["o-"],
    "meleeslamcancel" : ["o-"],
    "overheadslamcancel" : ["o-"],
    "overheadburn" : ["o-"],
    "overburn" : ["o-"],
    "ohburn" : ["o-"],
    "downslamburn" : ["o-"],
    "slamburn" : ["o-"],
    "meleeoverheadslamburn" : ["o-"],
    "meleeoverheadburn" : ["o-"],
    "meleeoverburn" : ["o-"],
    "meleeohburn" : ["o-"],
    "meleedownslamburn" : ["o-"],
    "meleeslamburn" : ["o-"],

    "nostick" : ["a-"]
}

SEQUENCE_NAMES = {
    "shortplink" : ["a", "o"],
    "fastplink" : ["a", "o"],
    "autoplink" : ["a", "o"],
    "longplink" : ["w", "t", "o"],
    "plink" : ["w", "t", "o"],
    "doubleplink" : ["w", "t", "a", "o"],
    "doubleswingoverhead" : ["w", "t", "a", "o"],
    "dsoverhead" : ["w", "t", "a", "o"],
    "dsoh" : ["w", "t", "a", "o"],

    "uniquetwohit" : ["a", "p", "+", "o"],
    "unique2hit" : ["a", "p", "+", "o"],
    "u2h" : ["a", "p", "+", "o"],
    "uniquethreehit" : ["w", "p", "p", "+", "o"],
    "unique3hit" : ["w", "p", "p", "+", "o"],
    "u3h" : ["w", "p", "p", "+", "o"],
}

COMBO_NAMES = {
    "tGu" : "Bread & Butter",
    "tGuwtt" : "Bread & Butter Tracers",
    "tGuwto" : "Bread & Butter Long Plink",
    "tGuao" : "Bread & Butter Short Plink",
    "tGuao" : "Bread & Butter Short Plink",
    "tGuwtao" : "Bread & Butter Double Plink",
    "tGup" : "Bread & Butter Punch",
    "tGutp" : "Reverse Panther Combo",
    "tGuwpp+o" : "Bread & Butter Unique 3 Hit",
    "tGwtuwt" : "Weave Combo",
    
    "tGptu" : "Panther Combo",
    "tGaptu" : "Fast Panther Combo",
    "tGaotu" : "Overhead Panther Combo",

    "tptu" : "One Two",
    "totu" : "Slam Combo",
    "otu" : "The Opener",
    "otuwtt" : "The Opener Tracers",
    "otuao" : "The Opener Short Plink",
    "otuwto" : "The Opener Long Plink",
    "otuwtao" : "The Opener Double Plink",

    "otaptu" : "Overhead Burst",
    "otgwtu" : "Master Masher",
    "otgwtuwto" : "Fantastic Killer",

    "tgptu" : "Sekkombo",
    "tgotu" : "Reverse Yo-Yo",
    "tgktu" : "Grip Kick Rip",
    "tgptapt" : "Short Hydro Combo",
    "tgptaptu" : "Hydro Combo",
    "tptaptu" : "No Pull Hydro Combo",

    "to+G+u" : "Saporen FFAmestack",
    "otG+u" : "Fast FFAmestack",

    "gwtuwto" : "Yo-Yo",
    "gwtuwtao" : "Double Plink Yo-Yo",
    "tguwto" : "Pre-Tag Yo-Yo",
    "gwtuo-tp" : "Agni-Kai Yo-Yo",

    "tuwtGu" : "Driveby",
    "twGuot" : "Bald Slam",
    "uwtGo" : "Vortex",
    "o+tgatu" : "Evil Combo",

    "tGuS" : "Noob Combo",
    "tGuwtS" : "Bread & Butter Symbiote Weave",
    "tgptSaptu" : "Matchydrokunsekkombiotombo",
    "otSatu" : "Symbiotic Opener",

    "CotBuE" : "Super Opener",
    "CotBuaEo" : "Super Opener Short Plink",
    "CtGBuE" : "Super Bread & Butter",
    "CtGBuaEo" : "Super Bread & Butter Short Plink",
    "CgBptuE" : "Tracer Replacer",
    "CtgBptuE" : "Super Sekkombo",
    "CtgBptuaEo" : "Super Sekkombo Short Plink",
    "CgBwtuwt" : "Short Super Yo-Yo",
    "CgBwtuwto" : "Super Yo-Yo",
    "CotBG+uE" : "Super Stack",
    "CotBG+uEp" : "Super Stack Punch",
    "CotBG+uaEo" : "Super Stack Short Plink"
}