from karen.actions.actionData import GOH_HIT_DISPLACE_DELAY

COMBO_ACTION_SYMBOLS = {
    "p" : ["p"],
    "k" : ["k"],
    "o" : ["o"],
    "t" : ["t"],
    "w" : ["w"],
    "s" : ["w"],
    "a" : ["a"],
    "g" : ["g"],
    "G" : ["G"],
    "u" : ["u"],
    "S" : ["S"],
    "V" : ["V"],
    "v" : ["V"],
    "C" : ["C"],
    "c" : ["C"],
    "B" : ["B"],
    "b" : ["B"],
    "E" : ["E"],
    "e" : ["E"],
    "+" : ["+"],
    "-" : ["-"],
    "f" : ["G", "+", "u"],
    "j" : ["u", "+", "w", "+", "G"]
}

COMBO_ACTION_NAMES = {
    "punch" : ["p"],
    "melee" : ["p"],
    "meleepunch" : ["p"],

    "kick" : ["k"],
    "meleekick" : ["k"],

    "overheadslam" : ["o"],
    "overhead" : ["o"],
    "over" : ["o"],
    "oh" : ["o"],
    "downslam" : ["o"],
    "slam" : ["o"],
    "meleeoverheadslam" : ["o"],
    "meleeoverhead" : ["o"],
    "meleeover" : ["o"],
    "meleeoh" : ["o"],
    "meleedownslam" : ["o"],
    "meleeslam" : ["o"],

    "tracer" : ["t"],
    "webtracer" : ["t"],
    "cluster" : ["t"],
    "webcluster" : ["t"],

    "swingwhiff" : ["w"],
    "webswingwhiff" : ["w"],
    "whiff" : ["w"],
    "webwhiff" : ["w"],
    "swing" : ["w"],
    "webswing" : ["w"],

    "autoswing" : ["a"],
    "autowebswing" : ["a"],
    "auto" : ["a"],
    "autoweb" : ["a"],
    "simpleswing" : ["a"],
    "simplewebswing" : ["a"],
    "simple" : ["a"],
    "simpleweb" : ["a"],
    "easyswing" : ["a"],
    "easywebswing" : ["a"],
    "easy" : ["a"],
    "easyweb" : ["a"],
    "highswing" : ["a"],
    "highwebswing" : ["a"],

    "getoverhere" : ["g"],
    "goh" : ["g"],
    "web pull" : ["g", f"[{GOH_HIT_DISPLACE_DELAY}f]"],
    "pull" : ["g", f"[{GOH_HIT_DISPLACE_DELAY}f]"],

    "getoverheretargeting" : ["G"],
    "getoverheretargetting" : ["G"],
    "goht" : ["G"],

    "uppercut" : ["u"],
    "upper" : ["u"],
    "amazingcombo" : ["u"],

    "symbiote" : ["S"],
    "symbiot" : ["S"],

    "venom" : ["V"],
    "venomsymbiote" : ["V"],
    "venomsymbiot" : ["V"],
    "upgradedsymbiote" : ["V"],
    "upgradedsymbiot" : ["V"],

    "clap" : ["C"],
    "peniclap" : ["C"],

    "webbomb" : ["B"],
    "bomb" : ["B"],
    "peniwebbomb" : ["B"],
    "penibomb" : ["B"],

    "explosion" : ["E"],
    "webexplosion" : ["E"],
    "exp" : ["E"],
    "peniexplosion" : ["E"],
    "peniwebexplosion" : ["E"],
    "peniexp" : ["E"],

    "ffamestack" : ["G", "+", "u"],
    "ffame" : ["G", "+", "u"],

    "punchsaporen" : ["p" , "+", "G"],
    "punchsaporentech" : ["p" , "+", "G"],

    "kicksaporen" : ["k" , "+", "G"],
    "kicksaporentech" : ["k" , "+", "G"],

    "overheadslamsaporen" : ["o" , "+", "G"],
    "overheadslamsaporentech" : ["o" , "+", "G"],
    "overheadsaporen" : ["o" , "+", "G"],
    "overheadsaporentech" : ["o" , "+", "G"],
    "ohsaporen" : ["o" , "+", "G"],
    "ohsaporentech" : ["o" , "+", "G"],
    "downslamsaporen" : ["o" , "+", "G"],
    "downslamsaporentech" : ["o" , "+", "G"],
    "slamsaporen" : ["o" , "+", "G"],
    "slamsaporentech" : ["o" , "+", "G"],
    "saporen" : ["o" , "+", "G"],
    "saporentech" : ["o" , "+", "G"],

    "punchsaporenffamestack" : ["p", "+", "G", "+", "u"],
    "punchsaporenffame" : ["p", "+", "G", "+", "u"],
    "punchsapstack" : ["p", "+", "G", "+", "u"],

    "kicksaporenffamestack" : ["k", "+", "G", "+", "u"],
    "kicksaporenffame" : ["k", "+", "G", "+", "u"],
    "kicksapstack" : ["k", "+", "G", "+", "u"],

    "overheadslamsaporenffamestack" : ["o", "+", "G", "+", "u"],
    "overheadslamsaporenffame" : ["o", "+", "G", "+", "u"],
    "overheadslamsapstack" : ["o", "+", "G", "+", "u"],
    "overheadsaporenffamestack" : ["o", "+", "G", "+", "u"],
    "overheadsaporenffame" : ["o", "+", "G", "+", "u"],
    "overheadsapstack" : ["o", "+", "G", "+", "u"],
    "ohsaporenffamestack" : ["o", "+", "G", "+", "u"],
    "ohsaporenffame" : ["o", "+", "G", "+", "u"],
    "ohsapstack" : ["o", "+", "G", "+", "u"],
    "downslamsaporenffamestack" : ["o", "+", "G", "+", "u"],
    "downslamsaporenffame" : ["o", "+", "G", "+", "u"],
    "downslamsapstack" : ["o", "+", "G", "+", "u"],
    "slamsaporenffamestack" : ["o", "+", "G", "+", "u"],
    "slamsaporenffame" : ["o", "+", "G", "+", "u"],
    "slamsapstack" : ["o", "+", "G", "+", "u"],
    "saporenffamestack" : ["o", "+", "G", "+", "u"],
    "saporenffame" : ["o", "+", "G", "+", "u"],
    "sapstack" : ["o", "+", "G", "+", "u"],

    "spacejam" : ["u", "+", "w", "+", "G"],

    "punchreversetrigger" : ["p", "+", "t"],
    "punchrt" : ["p", "+", "t"],
    "reversetrigger" : ["p", "+", "t"],
    "rt" : ["p", "+", "t"],

    "kickreversetrigger" : ["k", "+", "t"],
    "kickrt" : ["k", "+", "t"],

    "overheadslamreversetrigger" : ["o", "+", "t"],
    "overheadslamrt" : ["o", "+", "t"],
    "overheadreversetrigger" : ["o", "+", "t"],
    "overheadrt" : ["o", "+", "t"],
    "ohreversetrigger" : ["o", "+", "t"],
    "ohrt" : ["o", "+", "t"],
    "downslamreversetrigger" : ["o", "+", "t"],
    "downslamrt" : ["o", "+", "t"],
    "slamreversetrigger" : ["o", "+", "t"],
    "slamrt" : ["o", "+", "t"],

    "uniquestack" : ["p", "+", "o"],
    "uniquepunchstack" : ["p", "+", "o"],
    "uniquepunchoverheadslamstack" : ["p", "+", "o"],
    "uniquepunchoverheadstack" : ["p", "+", "o"],
    "uniquepunchohstack" : ["p", "+", "o"],
    "uniquepunchdownslamstack" : ["p", "+", "o"],
    "uniquepunchslamstack" : ["p", "+", "o"],
    "uniquetwohit" : ["p", "+", "o"],
    "unique2hit" : ["p", "+", "o"],
    "u2h" : ["p", "+", "o"],

    "uniquethreehit" : ["w", "p", "p", "+", "o"],
    "unique3hit" : ["w", "p", "p", "+", "o"],
    "u3h" : ["w", "p", "p", "+", "o"],

    "uniquekickstack" : ["p", "+", "o"],
    "uniquekickoverheadslamstack" : ["p", "+", "o"],
    "uniquekickoverheadstack" : ["p", "+", "o"],
    "uniquekickohstack" : ["p", "+", "o"],
    "uniquekickdownslamstack" : ["p", "+", "o"],
    "uniquekickslamstack" : ["p", "+", "o"],

    "gohbombstack" : ["g", "+", "B"],
    "getoverherebombstack" : ["g", "+", "B"],
    "pullbombstack" : ["g", "+", "B"],
    "webpullbombstack" : ["g", "+", "B"],

    "gohtbombstack" : ["G", "+", "B"],
    "getoverheretargetingbombstack" : ["G", "+", "B"],
    "getoverheretargettingbombstack" : ["G", "+", "B"],

    "punchexplosionsaporenffamestack" : ["p", "+", "E", "+", "G", "+", "u"],
    "punchexplosionsaporenffame" : ["p", "+", "E", "+", "G", "+", "u"],
    "punchexplosionsapstack" : ["p", "+", "E", "+", "G", "+", "u"],

    "kickexplosionsaporenffamestack" : ["k", "+", "E", "+", "G", "+", "u"],
    "kickexplosionsaporenffame" : ["k", "+", "E", "+", "G", "+", "u"],
    "kickexplosionsapstack" : ["k", "+", "E", "+", "G", "+", "u"],

    "overheadslamexplosionsaporenffamestack" : ["o", "+", "E", "+", "G", "+", "u"],
    "overheadslamexplosionsaporenffame" : ["o", "+", "E", "+", "G", "+", "u"],
    "overheadslamexplosionsapstack" : ["o", "+", "E", "+", "G", "+", "u"],
    "overheadexplosionsaporenffamestack" : ["o", "+", "E", "+", "G", "+", "u"],
    "overheadexplosionsaporenffame" : ["o", "+", "E", "+", "G", "+", "u"],
    "overheadexplosionsapstack" : ["o", "+", "E", "+", "G", "+", "u"],
    "ohexplosionsaporenffamestack" : ["o", "+", "E", "+", "G", "+", "u"],
    "ohexplosionsaporenffame" : ["o", "+", "E", "+", "G", "+", "u"],
    "ohexplosionsapstack" : ["o", "+", "E", "+", "G", "+", "u"],
    "downslamexplosionsaporenffamestack" : ["o", "+", "E", "+", "G", "+", "u"],
    "downslamexplosionsaporenffame" : ["o", "+", "E", "+", "G", "+", "u"],
    "downslamexplosionsapstack" : ["o", "+", "E", "+", "G", "+", "u"],
    "slamexplosionsaporenffamestack" : ["o", "+", "E", "+", "G", "+", "u"],
    "slamexplosionsaporenffame" : ["o", "+", "E", "+", "G", "+", "u"],
    "slamexplosionsapstack" : ["o", "+", "E", "+", "G", "+", "u"],
    "explosionsaporenffamestack" : ["o", "+", "E", "+", "G", "+", "u"],
    "explosionsaporenffame" : ["o", "+", "E", "+", "G", "+", "u"],
    "explosionsapstack" : ["o", "+", "E", "+", "G", "+", "u"],

    "uniquepunchexplosionoverheadslamstack" : ["p", "+", "E", "+", "o"],
    "uniquepunchexplosionoverheadstack" : ["p", "+", "E", "+", "o"],
    "uniquepunchexplosionohstack" : ["p", "+", "E", "+", "o"],
    "uniquepunchexplosiondownslamstack" : ["p", "+", "E", "+", "o"],
    "uniquepunchexplosionslamstack" : ["p", "+", "E", "+", "o"],

    "uniquekickexplosionstack" : ["p", "+", "E", "+", "o"],
    "uniquekickexplosionoverheadslamstack" : ["p", "+", "E", "+", "o"],
    "uniquekickexplosionoverheadstack" : ["p", "+", "E", "+", "o"],
    "uniquekickexplosionohstack" : ["p", "+", "E", "+", "o"],
    "uniquekickexplosiondownslamstack" : ["p", "+", "E", "+", "o"],
    "uniquekickexplosionslamstack" : ["p", "+", "E", "+", "o"],

    "punchcancel" : ["p-"],
    "meleecancel" : ["p-"],
    "meleepunchcancel" : ["p-"],
    "punchburn" : ["p-"],
    "meleeburn" : ["p-"],
    "meleepunchburn" : ["p-"],

    "kickcancel" : ["k-"],
    "meleekickcancel" : ["k-"],
    "kickburn" : ["k-"],
    "meleekickburn" : ["k-"],

    "overheadslamcancel" : ["o-"],
    "overheadcancel" : ["o-"],
    "overcancel" : ["o-"],
    "ohcancel" : ["o-"],
    "downslamcancel" : ["o-"],
    "slamcancel" : ["o-"],
    "meleeoverheadslamcancel" : ["o-"],
    "meleeoverheadcancel" : ["o-"],
    "meleeovercancel" : ["o-"],
    "meleeohcancel" : ["o-"],
    "meleedownslamcancel" : ["o-"],
    "meleeslamcancel" : ["o-"],
    "overheadslamcancel" : ["o-"],
    "overheadburn" : ["o-"],
    "overburn" : ["o-"],
    "ohburn" : ["o-"],
    "downslamburn" : ["o-"],
    "slamburn" : ["o-"],
    "meleeoverheadslamburn" : ["o-"],
    "meleeoverheadburn" : ["o-"],
    "meleeoverburn" : ["o-"],
    "meleeohburn" : ["o-"],
    "meleedownslamburn" : ["o-"],
    "meleeslamburn" : ["o-"],

    "nostick" : ["a-"]
}

COMBO_NAMES = {

}